---
    version: "3"
    services: 
      wordpress: 
        image: "wordpress"
        restart: "unless-stopped"
        volumes: 
          - "./wordpress:/var/www/html/"
        depends_on: 
          - "mysql"
        ports: 
          - "80:80"
        environment: 
          WORDPRESS_DB_PASSWORD: "root"
      mysql: 
        image: "mysql:5"
        restart: "unless-stopped"
        volumes: 
          - "mysql_db:/var/lib/mysql"
        ports: 
          - "3306:3306"
          - "33060:33060"
        environment: 
          MYSQL_ROOT_PASSWORD: "root"
      phpmyadmin: 
        image: "phpmyadmin/phpmyadmin"
        ports: 
          - "8001:80"
        depends_on: 
          - "mysql"
        environment: 
          PMA_HOST: "mysql"
          PMA_USER: "root"
          PMA_PASSWORD: "root"
    volumes: 
      mysql_db: 